### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by abeidahmed**
- Ask for the player's name
- Check if player names are identical. If they are, prompt the player to register for a different name
- Show the board to the user
- Write game instructions

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @abeidahmed :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

Your game only asks for player name and return the board.
See below for expected behaviour of the game in this milestone.

- [x] In this step students are supposed to only **mock** the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (`gets.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no mater who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [x] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

  * [x] `[OPTIONAL]` game asks players for their names
  * [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
  * [x] `[REQUIRED]` game asks the player to select from available moves
  * [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
  * [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
  * [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
  * [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
  * [x] `[REQUIRED]` game repeats all actions for the next player's move
 
##### Implementation details

* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x] Inside the loop, student should call actions repeated for each move
* [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
### Please, make the requested changes and submit for another review
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by abeidahmed** [comment]
> # Status: Changes Required ♻️
> ## Hi @abeidahmed 👋
> You've done well so far 👍 and I commend you for that 👏
> However, there are still some changes to be made before this milestone can be approved.
> 
> ## REQUIRED
> Your game only asks for player name and return the board.
> See below for expected behaviour of the game in this milestone.
> 
> * [ ]  In this step students are supposed to only **mock** the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (`gets.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no mater who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
> * [ ]  Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
>   
>   * [x]  `[OPTIONAL]` game asks players for their names
>   * [ ]  `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
>   * [ ]  `[REQUIRED]` game asks the player to select from available moves
>   * [ ]  `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
>   * [ ]  `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
>   * [ ]  `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
>   * [ ]  `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
>   * [ ]  `[REQUIRED]` game repeats all actions for the next player's move
> 
> ##### Implementation details
> * [ ]  A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
> * [ ]  Inside the loop, student should call actions repeated for each move
> * [ ]  A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
> 
> ```ruby
> game_on = true
> 
> # initial instructions for player
> 
> while game_on
>   # loop for each move
> 
>   if winner # and/or draw (the exact condition in this milestone is not important)
>     game_on = false
>   end
> end
> ```
> 
> ### Please, make the requested changes and submit for another review
> ## Happy Coding 💻
> _Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
> **Elijah O. Ayandokun**
> [Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

Ok. So the entire flow has to be made with all the instruction. Does not matter if the board is updated or not. I just need to keep on looping till `game_ended = false` and at last end the game manually? Is that so?

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @abeidahmed  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

- [x] Your game does not inform the players if their move is a winning move or a draw move.
- [x] Your game should also inform the player if their moves are valid or not (without computing what a valid move is)
- [x] Your game should repeat all those actions for the next player's move
- [x] You shouldn't display this:
image

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by abeidahmed** [comment]
> # Status: Changes Required ♻️
> ## Hi @abeidahmed 👋
> You've done well so far 👍 and I commend you for that 👏
> However, there are still some changes to be made before this milestone can be approved.
> 
> ## REQUIRED
> * [ ]  Your game does not inform the players if their move is a winning move or a draw move.
> * [ ]  Your game should also inform the player if their moves are valid or not (without computing what a valid move is)
> * [ ]  Your game should repeat all those actions for the next player's move
> * [ ]  You shouldn't display this:
>   image
> 
> ### Make the requested changes and submit for another review.
> ## Happy Coding 💻
> _Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
> **Elijah O. Ayandokun**
> [Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

How should I tell the user if their move is winning or not? Just `puts "You are winning"`? I don't understand what you're saying. 
2021-01-06 16_28_34-User interface by abeidahmed · Pull Request #2 · abeidahmed_tic-tac-toe
You just said here, that I should tell the user if the selected move is invalid. Now you're saying I shouldn't display that. Please clarify on this.

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
