### PR TITLE
Test feature

### PR DESCRIPTION
**Pull request by abeidahmed**
- Add `spec` files to test the game.
- Update `README.md` to credit the authors.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @abeidahmed  :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed the tic tac toe game. However your code review request is marked as invalid due to the following reasons:

1. The submitted Pull Request contains only the changes in readme file, => this means you should have submitted the Pull Request which contains actual spec tests that you wrote.
2. I can see that your project already has tests in it, but in the other Pull Request which is already merged, => you wrote tests in [this Pull Request](https://github.com/abeidahmed/tic-tac-toe/pull/5) unfortunately you already merged this Pull Request hence we cannot review it.

_`Action to be taken:` While you are preparing for the other code review request submission, we need you to submit an open Pull Request which contains the actual tests, I mean the Pull Request in which you wrote the tests, and it needs to be open => (not merged and not closed)_

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by abeidahmed** [comment]
> # Status: Invalid Submission ❌ 😞 🛑
> ## Hello @abeidahmed 🤝 🤝 🤝
> Thank you for submitting a code review request. And congratulations on that you have completed the tic tac toe game. However your code review request is marked as invalid due to the following reasons:
> 
> 1. The submitted Pull Request contains only the changes in readme file, => this means you should have submitted the Pull Request which contains actual spec tests that you wrote.
> 2. I can see that your project already has tests in it, but in the other Pull Request which is already merged, => you wrote tests in [this Pull Request](https://github.com/abeidahmed/tic-tac-toe/pull/5) unfortunately you already merged this Pull Request hence we cannot review it.
> 
> _`Action to be taken:` While you are preparing for the other code review request submission, we need you to submit an open Pull Request which contains the actual tests, I mean the Pull Request in which you wrote the tests, and it needs to be open => (not merged and not closed)_
> 
> Happy coding!!!
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

@descholar-ceo I commented the test and uncommented it out, made a pull request. Please check.

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @abeidahmed  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the almost all minimal requirements to this project
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] You should have one it block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/auth/sign-in/?next=/library/fast-track-curriculum/69047/path/step/59566098/))
- [x] Add tests for `print_board` method from `lib/board.rb` file
- [x] Add tests`show_updated_board` method from `lib/board.rb` file

### :warning: For your future projects, don't ever submit a pull request which contains codes which are already merged to the main codebase, that's a violation of the correct `git/github` workflow.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by ElijahTobs — APPROVED** [review]
# Status: Approved! :tada: 

## Congratulations! @abeidahmed 

Good job implementing the changes requested by the previous TSE.

## You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Pull request merged**
